### ISSUE TITLE
Add content under 'july_subjects'

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Ono-MBA-New-Site#15]
Please add the next line of content under july_subjects.

*Content in Hebrew brakes here. Content will provide via email - Mladen's.

Set font size to 0.8 rem.

![image](https://user-images.githubusercontent.com/26923359/28315429-14be46a2-6bc7-11e7-8823-44c2c1b8d729.png)

**Comment by MeanEYE** [comment]
Font-size won't be touched though.

**Comment by talovdat** [comment]
Pause that issue. Might Close it due to Client campaign changes.

**Comment by talovdat** [comment]
Client approve, proceed to add content.

**Comment by MeanEYE** [comment]
This is an article in the backend. Further more, you attached image and expect me to type hebrew.

**Comment by talovdat** [comment]
Wrong repository! 
moved the issue to Ono-College-New-Site
