### ISSUE TITLE
Increase article width 

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Ono-MBA-New-Site#16]
URL: http://openday.ono.ac.il/july

We need to increase the article width, so the whole text will fit. 

![image](https://user-images.githubusercontent.com/26923359/36352425-77503db8-14c1-11e8-97eb-0acfaa4a5c57.png)

**Comment by VladimirWebDev** [comment]
This is not correct repository. There is no July page in here. Ono-College-New-Site is correct one. Ill push changes there. That is only Ono repository with July page, however last thing I did there is to add November page and redirect to it, but it still points to July page, I don't now were changes deployed back then.
